// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkerService_GetTaskRPC_FullMethodName     = "/server.WorkerService/GetTaskRPC"
	WorkerService_SendResultRPC_FullMethodName  = "/server.WorkerService/sendResultRPC"
	WorkerService_WorkerStateRPC_FullMethodName = "/server.WorkerService/WorkerStateRPC"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServiceClient interface {
	// методы, которые можно будет реализовать и использовать
	GetTaskRPC(ctx context.Context, in *GetTask, opts ...grpc.CallOption) (*GetTaskResponse, error)
	SendResultRPC(ctx context.Context, in *SendResult, opts ...grpc.CallOption) (*SendResultResponse, error)
	WorkerStateRPC(ctx context.Context, in *WorkerState, opts ...grpc.CallOption) (*WorkerStateResp, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) GetTaskRPC(ctx context.Context, in *GetTask, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetTaskRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SendResultRPC(ctx context.Context, in *SendResult, opts ...grpc.CallOption) (*SendResultResponse, error) {
	out := new(SendResultResponse)
	err := c.cc.Invoke(ctx, WorkerService_SendResultRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) WorkerStateRPC(ctx context.Context, in *WorkerState, opts ...grpc.CallOption) (*WorkerStateResp, error) {
	out := new(WorkerStateResp)
	err := c.cc.Invoke(ctx, WorkerService_WorkerStateRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility
type WorkerServiceServer interface {
	// методы, которые можно будет реализовать и использовать
	GetTaskRPC(context.Context, *GetTask) (*GetTaskResponse, error)
	SendResultRPC(context.Context, *SendResult) (*SendResultResponse, error)
	WorkerStateRPC(context.Context, *WorkerState) (*WorkerStateResp, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServiceServer struct {
}

func (UnimplementedWorkerServiceServer) GetTaskRPC(context.Context, *GetTask) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskRPC not implemented")
}
func (UnimplementedWorkerServiceServer) SendResultRPC(context.Context, *SendResult) (*SendResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResultRPC not implemented")
}
func (UnimplementedWorkerServiceServer) WorkerStateRPC(context.Context, *WorkerState) (*WorkerStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerStateRPC not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_GetTaskRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetTaskRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetTaskRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetTaskRPC(ctx, req.(*GetTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SendResultRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SendResultRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SendResultRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SendResultRPC(ctx, req.(*SendResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_WorkerStateRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).WorkerStateRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_WorkerStateRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).WorkerStateRPC(ctx, req.(*WorkerState))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskRPC",
			Handler:    _WorkerService_GetTaskRPC_Handler,
		},
		{
			MethodName: "sendResultRPC",
			Handler:    _WorkerService_SendResultRPC_Handler,
		},
		{
			MethodName: "WorkerStateRPC",
			Handler:    _WorkerService_WorkerStateRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
